### ISSUE TITLE
Deleted group is allways again inserted in Configuration-Manager by saving

### ISSUE THREAD

**Issue by jdgf** [JoomGallery/JoomGallery#102]
There are only two gruops when opening configaration manager (pic joomgallery_fehler_01). 
![joomgallery_fehler_01](https://cloud.githubusercontent.com/assets/20367716/16706954/fdf2eb72-45bf-11e6-8c7b-6dd69a3a0aec.jpg)

But after saving there is a new group and a hint that I should delete the new group because the group doesn't exist. (pic joomgallery_fehler_02).
![joomgallery_fehler_02](https://cloud.githubusercontent.com/assets/20367716/16706955/fdf69c40-45bf-11e6-980d-ccfd076f3458.jpg)

Then I delete the 3. group. Although I have deleted the group more than 30 times (see no. 40 at the right side), the group is inserted again.

http://www.forum.joomgallery.net/index.php/topic,6413.0.html

**Comment by Erftralle** [comment]
Please test #105 to fix this issue.

**Comment by Chraneco** [comment]
This was fixed with #105.
