### ISSUE TITLE
Replace Gallery Icons with Fontawesome Icons

### ISSUE THREAD

**Issue by J-Evolve** [JoomGallery/JoomGallery#109]
Hello folks,
the current gallery icons feel a bit outdated so I would suggest to replace them with fontawesome icons or give an option to choose between default / fontawesome / upload-own icons.
This would improve customization of joomgallery a lot.
I hope i didn't miss something and this is already implemented :)

Kind regards,
Vole

**Comment by Chraneco** [comment]
Please check out the bootstrap layouts that we provide here on GitHub. They use the icon sets that come with the template.
