### ISSUE TITLE
Interface.php - line break in upload date

### ISSUE THREAD

**Issue by MrMusic** [JoomGallery/JoomGallery#111]
When displaying the upload date, e.g. in JoomImages, a fixed line break (<br />) is inserted. Is this intended? (Interface.php, line 713)
See also http://www.forum.joomgallery.net/index.php/topic.5853.0.html

**Comment by Chraneco** [comment]
This code is really old, I'm not sure why the line break was added there, but there must have been a reason. I'm not sure whether we disrupt other people's websites if we just remove it now.

**Comment by Chraneco** [comment]
After thinking about it, I would say we should actually remove that line break there. It is an inconsistency.
