### ISSUE TITLE
Skip category view

### ISSUE THREAD

**Issue by anmevissen** [JoomGallery/JoomGallery#117]
In the configuration manager you can choose in front end settings to skip the category view. I've created 4 categories and put some test images in those 4 categories. The categories have fixed thumbnails. (own choice). If I click on the category in the gallery view, it opens the fancybox directly as wanted, but it doesn't show the images of that category, but the 4 thumbnails of the categories, twice. So I have 8 thumbnail images and no category images. Is there another setting I have to configurate? I don't want the category view. Thanks

**Comment by Erftralle** [comment]
The option **_Frontend Settings > General Settings > Skip category view_** is only working in a sensefull manner by setting **_Category View > General Settings > Entering Detail View_** to **_Default View_**.

**Comment by anmevissen** [comment]
Thanks. I'm wondering if this is gonna be changed in the future?

**Comment by Chraneco** [comment]
Please submit a feature request for that here: https://joomgallery.uservoice.com/
