### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by balping** [JoomGallery/JoomGallery#119]
An attacker has to be able to login to the admin panel first, so this is not too bad, but better to fix it.

The values of `jg_firstorder`, `jg_secondorder`, `jg_thirdorder` are not checked, before directly inserting them into a query.

https://github.com/JoomGallery/JoomGallery/blob/348f03ede7912015f879d27eb53c997cc15b77ff/components/com_joomgallery/models/category.php#L251

https://github.com/JoomGallery/JoomGallery/blob/348f03ede7912015f879d27eb53c997cc15b77ff/components/com_joomgallery/models/detail.php#L516

**Comment by Chraneco** [comment]
Fixed with the above referenced pull request, thanks!
