### ISSUE TITLE
Future of Joomgallery?

### ISSUE THREAD

**Issue by Hackwar** [JoomGallery/JoomGallery#120]
Hi,
I'm trying to contact someone from the team, but so far I don't really know how. I tried to reach mab, but got no response so far. Maybe you can get in touch with me via mail?  Development seems to have stalled a bit and I'd like to help get it moving again.

Hi,
ich versuche seit einigen Tagen jemanden vom Team zu erreichen, allerdings ist mir das bisher nicht geglückt, vor allem weil ich nicht so ganz weiss, wie. Ich habe mab eine Mail geschrieben, allerdings bisher noch keine Antwort erhalten. Vielleicht kann sich jemand von euch bei mir per Mail melden? Die Entwicklung der JG scheint ein bisschen eingeschlafen zu sein und ich würde das gerne wieder ins rollen bringen.

Hannes Papenberg
info@joomlager.de

**Comment by Erftralle** [comment]
Hi,
auch wenn dieses Thema schon geschlossen wurde - gab es einen Kontakt? 
Ich würde auch gerne wissen, ob es eine (geplante) Zukunft für die JoomGallery gibt.

**Comment by Hackwar** [comment]
Hi, ja, Kontakt wurde aufgenommen und es gibt eine Zukunft. 😉 Ich hab ein paar Sachen schon abgesprochen und in den nächsten Tagen/Wochen wird es hier etwas Aktivität geben.

**Comment by Hackwar** [comment]
Die genauen Details sind noch nicht klar, weshalb ich jetzt hier nicht einfach wild drauf los schreiben will.

**Comment by Erftralle** [comment]
Vielen Dank für die Info.

> ... und es gibt eine Zukunft.

Das freut mich 😄 .
