### ISSUE TITLE
Wrong upload links

### ISSUE THREAD

**Issue by Webdongle** [JoomGallery/JoomGallery#129]
In the front end the 'Single image' tab displays the 'Batch uploads' screen and visa versa
In the admin control panel 'Image upload' menu item displays the 'Batch uploads' screen and visa versa

**Comment by Erftralle** [comment]
I can not confirm this error. For me, the links are not reversed.

**Comment by Webdongle** [comment]
OK ... got it

In the frontend
'Single images' in upload form = select one at a time and upload all of them in one go ('a batch').
'Batch Upload' in upload form = select one zip file and upload a single file
Whereas in the backend
'Single Upload' = select one at a time and upload all of them in one go ('a batch').  But the word 'Batch' (in Batch Upload) doesn't refer to neither the number of files selected nor the number of files uploaded ... it refers to the number of files in the zip.

Maybe it's my understanding of the English grammar is incorrect but to me:
'Single Upload' means uploading a single file at a time whereas 'Batch Upload' means several files (regardless of them being selected singularly) uploaded at the same time.

No matter ... there is always language override.  Thanks for your time to answer,
