### ISSUE TITLE
RFC: Set minimal Browser versions for support

### ISSUE THREAD

**Issue by Hackwar** [JoomGallery/JoomGallery#130]
Looking at the code, I've come across at least one place which still caters for old IE versions. Looking at the usage statistics on CanIUse, everything below IE8 is used so rarely that it can't really be measured, and even the other versions below IE11 are next to never used. I'd like to propose to raise the minimum browser version for the JoomGallery to IE10 and thus to remove those special treatments for older versions of IE.

What do you think?

(P.S.: Kommunikation hier auf Deutsch oder Englisch?)

**Comment by Erftralle** [comment]
I think basically we should follow Joomla's prerequisites (https://docs.joomla.org/Joomla_Browser_Support).

**Comment by Chraneco** [comment]
I agree with Erftralle, that's a good point.

We should keep communication here in English so that as many people as possible can contribute.
