### ISSUE TITLE
How to change the title in your browser

### ISSUE THREAD

**Issue by Vitaliy214** [JoomGallery/JoomGallery#133]
Hello
Site users download images with the same name
This creates duplicate names in the search engine
How to add a page ID to a browser title

For example, the address page
w_w_w.com/foto-777.html
should have a title
`<title>Foto - 777</title>`

How do I do this on my site ???

**Comment by Chraneco** [comment]
When multiple pictures are uploaded JoomGallery provides a way to automatically add an image counter to the image title. This number would then show up in the page title as well.
