### ISSUE TITLE
Problem delete category in maintenance manager

### ISSUE THREAD

**Issue by MrMusic** [JoomGallery/JoomGallery#143]
If a category is deleted in the maintenance manager, the error message 'TableJoomgalleryCategories does not support ordering' appears. Nevertheless, the category is deleted. 
Deleting categories with containing images is not possible at all.

**Comment by Erftralle** [comment]
Please provide detailed information on how about to reproduce this issue. Thanks in advance.

**Comment by MrMusic** [comment]
>Please provide detailed information on how about to reproduce this issue. Thanks in advance.

Sorry, if I did not described it exactly.

**Testing instructions:**

- Create a category without images and with a 'wrong' owner (missing Joomla! user)
- Do a check in the maintenance manager
- Mark the category with the 'wrong' owner
- Select the batch job 'delete' and then 'apply'

Do the same test as above with a category that contains images.

**Comment by Erftralle** [comment]
Thanks @MrMusic for your detailed description. Pull request #144 should fix that.

**Comment by Chraneco** [comment]
Thanks!
