### ISSUE TITLE
Bild ersetzen

### ISSUE THREAD

**Issue by Isi88** [JoomGallery/JoomGallery#145]
Hallo,

beim Ersetzen eines Bildes bekomme ich immer diese Fehlermeldung:

> "Es ist ein Fehler aufgetreten!
> 
> 0 Too few arguments to function JoomFile::resizeImage(), 9 passed in /var/www/***/html/joomla/administrator/components/com_joomgallery/models/image.php on line 479 and exactly 10 expected

Grund der Ersetzung ist, das beim Drag'nDrop Upload alle "Hochkant"-Bilder in automatisch gedreht werden. Warum verstehe ich allerdings nicht.
Die Größenänderung habe ich in den Einstellungen deaktiviert.

Hoffentlich kann mit da jemand helfen. :)

Vielen Dank!

**Comment by Erftralle** [comment]
Vielen Dank!

#146 sollte das Problem beheben.

**Comment by Isi88** [comment]
Ja, hat geholfen!
