### ISSUE TITLE
Problem with Joomla 3.8.12

### ISSUE THREAD

**Issue by Elfangor93** [JoomGallery/JoomGallery#166]
There is a problem with a new security feature in Joomla 3.8.12. Error after pressing the save button.
The problem and a possible solution was discussed in the german comunity:
[https://forum.joomla.de/thread/6227-joomgallery-3-3-4-und-joomla-3-8-12/](https://forum.joomla.de/thread/6227-joomgallery-3-3-4-und-joomla-3-8-12/)

**Comment by af9** [comment]
Same for me in Joomla 3.9.4
