### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by FabianCernota** [JoomGallery/JoomGallery#29]
While install Joomgallery via package upload i get this error message:
JFolder: :files: Der Pfad ist kein Ordner! Pfad: /var/www/clients/client11/web18/web/administrator/components/com_joomgallery

JFolder: :files: Der Pfad ist kein Ordner! Pfad: /var/www/clients/client11/web18/web/administrator/components/com_joomgallery

JInstaller: :Install: Die XML-Installationsdatei konnte nicht gefunden werden.

JInstaller: :Install: Die XML-Installationsdatei konnte nicht gefunden werden.

Table 'usr11_db_db01.w1tf3_joomgallery_catg' doesn't exist SQL=ALTER TABLE `w1tf3_joomgallery_catg` DROP `ordering`;

**Comment by Chraneco** [comment]
Seems like JoomGallery was installed before. Please uninstall it completely before trying again. You will probably have to delete the JoomGallery entry in the #__extensions table.

**Comment by FabianCernota** [comment]
Thanks it works :+1:
