### ISSUE TITLE
Bulk / All Images actions in Control Panel

### ISSUE THREAD

**Issue by GJSchaller** [JoomGallery/JoomGallery#32]
I have a large gallery (10,000+ images across over 100 categories) - on occasion, I need to perform an operation to all of them, such as rebuilding thumbnails if my template changes.

Currently, the Maintenance Manager lets me check all items, but not modify them all.

Would it be possible to add a set of All Items tasks, either as Maintenance Manager items, or a Migration Scripts, that could rebuild all Thumbnails?

**Comment by Chraneco** [comment]
Please vote for or create a pull request for this here: https://joomgallery.uservoice.com/.
