### ISSUE TITLE
Direct image management by Owner/Admin from frontend

### ISSUE THREAD

**Issue by Quetzalthefirst** [JoomGallery/JoomGallery#46]
Hi

I have found the option to enable images publish / approval in front end by admin. But this option allow super admin only and the click for approval don't work when the same feature for publish/unpublish work well.

I have last version of Joom Galleyr and last version of Joomla.

Can you help me to enable approval for "joom galery admin" (with no backend access) in frontend.

Thank you

**Comment by Chraneco** [comment]
Hi,

approving images in the frontend is not yet possible.

Are you interested in programming this feature yourself? If yes, feel free to ask me any technical question about JoomGallery and open a pull request, I will try to help as much as I can.
If not, I will close this issue and would ask you to post/vote on this feature request on Uservoice: http://joomgallery.uservoice.com/

Regards
Chraneco

**Comment by Quetzalthefirst** [comment]
Ok...

I will check for programming this feature as soon as i have time for it 
this autumn.

I come back to you soon...

Normand
...

On 23/08/2015 12:19 PM, Patrick Alt wrote:
>
> Hi,
>
> approving images in the frontend is not yet possible.
>
> Are you interested in programming this feature yourself? If yes, feel 
> free to ask me any technical question about JoomGallery and open a 
> pull request, I will try to help as much as I can.
> If not, I will close this issue and would ask you to post/vote on this 
> feature request on Uservoice: http://joomgallery.uservoice.com/
>
> Regards
> Chraneco
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JoomGallery/JoomGallery/issues/46#issuecomment-133871378>.
>

-- 
Tout en restant Z, il est N* et Q et non pas Im de croire qu'il est C de comprendre en N la partie Q' de R!
(Traduction: Tout en restant relatif, il est naturel et rationnel et non pas imaginaire de croire qu'il est complexe de comprendre en entier la partie irrationnelle des réels!)

Normand Brousseau, B.Sc., M.Sc.
Solinfo enr.
Courriel: mailto:normandb@solinfo.ca
Pages web:
		http://www.solinfo.ca
	   	http://www.ambianceselecte.com


-----------------------------------------------------------------------

AVIS :
Ce message est confidentiel et à l'usage exclusif du destinataire. Toute autre personne est avisée qu'il lui est strictement interdit de le diffuser, distribuer ou reproduire. Si vous avez reçu ce message par erreur, veuillez nous en informer immédiatement par téléphone ou par courriel et effacer toute copie.

NOTICE:
This e-mail is confidential and intended for the exclusive use of the addressee. Any other person is strictly prohibited from disclosing, distributing or reproducing it. If you have received this e-mail by mistake, please notify us immediately by telephone or e-mail and delete all copies.

**Comment by Chraneco** [comment]
Closing because there were no further replies and because this should be handled as a feature request.
