### ISSUE TITLE
Wartungsmanager hat Problem mit Endung ".JPG"

### ISSUE THREAD

**Issue by Tanarri** [JoomGallery/JoomGallery#47]
JoomGallery: 3.2.2
Joomla: 3.4.3

Wenn ich den Wartungsmanager benutze, erscheinen unter "Waisen" ein paar Einträge, z.B folgende Datei verwaist ist:
/joomla3/images/joomgallery/details/galerie_2014_112/nacht_der_zwerge_113/nacht_der_zwerge_20140128_1563681891.JPG 
Wenn ich per FTP nachschaue, dann existiert diese Datei auch - korrekt!

Im Frontend kann ich dieses Bild auch anschauen (Thumnail und Detailansicht sind korrekt). Somit dürfte der Wartungsmanager diese Datei nicht als verwaist anzeigen.

Weitere Infos:
Folgende Dateien existierten auf dem Linux-Webserver:
/joomla3/images/joomgallery/details/galerie_2014_112/nacht_der_zwerge_113/nacht_der_zwerge_20140128_1563681891.JPG  <--- Endung ist gross  geschrieben!!
/joomla3/images/joomgallery/thumbnails/galerie_2014_112/nacht_der_zwerge_113/nacht_der_zwerge_20140128_1563681891.jpg   <--- Endung ist klein geschrieben!!
/joomla3/images/joomgallery/originals/galerie_2014_112/nacht_der_zwerge_113/nacht_der_zwerge_20140128_1563681891.JPG   <--- Endung ist gross geschrieben!!

Tabelle "j3_joomgallery"
SELECT * FROM `j3_joomgallery` WHERE `imgfilename` like '%1563681891%' 
imgfilename = 'nacht_der_zwerge_20140128_1563681891.JPG'
imgthumbname = 'nacht_der_zwerge_20140128_1563681891.jpg'

Alle Dateien im Wartungsmanager unter "Waisen" haben die Dateiendung "JPG" besitzen. Ich habe es geprüft und in den Verzeichnissen "originals" und "details" sind dies auch alle Dateien, die die Endung "JPG" haben.
Alle Dateien in den Verzeichnissen "originals" und "details" die eine Endung "jpg" haben erscheinen nicht unter "Waisen"

Es ist wohl ein Problem mit Gross-/Kleinschreibung
Benötigt ihr weitere Infos???

Gruß 
Eugen

**Comment by Erftralle** [comment]
Hallo Eugen,

ich kann das Problem bestätigen und habe mit Pull Request #51 eine Lösung angeboten.
Vielleicht magst du sie testen und ein Feedback geben. Danke!

**Comment by Tanarri** [comment]
Hi Erftralle,

danke für deine Antwort!
Ich habe deinen Pull Request #51 bei mir eingespielt und getestet.
Es funktioniert mit deinem Patch nun korrekt! Der Patch kommt ja bestimmt auch in das nächste Release :-)

Danke für die Lösung!

Gruß
Eugen

**Comment by Chraneco** [comment]
Hi zusammen,

ich bin mir nicht sicher, ob wir das damit wirklich schon erledigen können. Die Galerie konvertiert eigentlich alle Dateiendungen vor dem endgültigen Abspeichern in die Kleinschreibung konvertiert.
Der Wartungsmanager meldet dies korrekterweise als mögliches Problem, er scheint dafür nur noch nicht die richtige Lösung anzubieten.

Ich vermute, diese Bilder sind eventuell durch eine Migration in die Galerie gelangt?

**Comment by Tanarri** [comment]
Mit welcher Version (Joomla + JoomGallerie) ich die Bilder hochgeladen habe, kann ich leider nicht mehr sagen.
Sorry!

Gruß
Eugen

**Comment by Erftralle** [comment]
Hi,

> ich bin mir nicht sicher, ob wir das damit wirklich schon erledigen können. Die Galerie konvertiert eigentlich alle Dateiendungen vor dem endgültigen Abspeichern in die Kleinschreibung konvertiert.
Der Wartungsmanager meldet dies korrekterweise als mögliches Problem, er scheint dafür nur noch nicht die richtige Lösung anzubieten.

Im Fall von @Tanarri gibt es doch definitiv kein Problem, Datenbankeinträge und Dateisystemeinträge sind, was die Groß- und Kleinschreibung der Dateiendung betrifft, gleich.
Der Wartungsmanager erzeugt also eine Falschmeldung, der Patch korrigiert das.
Sollten, was ja bei @Tanarri nicht der Fall ist, Datenbankeinträge und Dateisystemeinträge nicht gleich sein, wird das vom Wartungsmanager separat noch erkannt. Dies ist zumindest auf Systemen der Fall, welches case sensitive Dateinamen beachten und verarbeiten können. Wo dies nicht der Fall ist, ist es egal.

Gibt es denn einen Fall, bei dem durch Anwendung des Patches der Wartungsmanager ein Problem nicht melden würde, welches aber tatsächlich ein Problem darstellt?

Gruß
Erftralle

**Comment by Chraneco** [comment]
Nein, du hast Recht. In case sensitiven Dateisystemen sollten die anderen Checks ein etwaiges Problem erkennen. Ich werde den Pull Request dann mergen.

Gruß
Chraneco
