### ISSUE TITLE
Split usage of language constant COM_JOOMGALLERY_COMMON_ORDERING

### ISSUE THREAD

**Issue by bobkid** [JoomGallery/JoomGallery#50]
Version: JoomGallery 3.2.2
Views: user categories and user panel view

The language constant COM_JOOMGALLERY_COMMON_ORDERING is used both as heading (default option) for the directionTable combobox and as option for the sortTable combobox. This makes it impossible to have the same text as in similar Joomla tables (e.g. Module manager table):
directionTable heading = Select the ordering
orderTable option = Ordering

Proposal is to add the following language constant: COM_JOOMGALLERY_COMMON_ORDER_DIRECTION="Select the ordering" and use that for the heading of the directionTable.
And let it replace the COM_JOOMGALLERY_COMMON_ORDERING constant in:
- components/com_joomgallery/views/usercategories/tmpl default.php 
- components/com_joomgallery/views/userpanel/tmpl default.php

**Comment by Chraneco** [comment]
This sounds like a good proposal. Please feel free to create a pull request for it.

**Comment by Erftralle** [comment]
Since we have a merged pull request #64 for this issue we could close here, right?
