### ISSUE TITLE
Split Config Tab "General Settings" -> "Additional Functions"

### ISSUE THREAD

**Issue by Chraneco** [JoomGallery/JoomGallery#56]
The term "Additional Functions" and this tab of the configuration manager contains very different kinds of settings.

Options like "Real name instead of username?", "Content Plugins" and "Default Itemid" should move to the tab "Frontend Settings" -> "General Settings".

Options "Ajax Category Selection" and "Disable unrequired checks" should be moved to a new sub-tab "Performance".

Also, a new option specifying the number of users which is used as a threshold for the different selection methods of users should be added into the "Performance" tab (see #55 for more info).

**Comment by Erftralle** [comment]
That's a good idea.  I will take over this task as soon as the master branch has been merged to the v3.3.0 branch.
One question: Shall we remove the empty tab "Additional Functions" or leave it for later use?

**Comment by Chraneco** [comment]
Great, thank you very much! I merged it.

I would get rid of that tab all together. It's too generic.

**Comment by Erftralle** [comment]
Since we have a merged pull request for this issue we could close here, right?

**Comment by Chraneco** [comment]
While the other two issues were closed automatically with the merge of branch v3.3.0 this one seems to have no connection, so I'm closing manually now, thanks!
