### ISSUE TITLE
Allow editing of config rows in advanced mode after creation

### ISSUE THREAD

**Issue by GenaBitu** [JoomGallery/JoomGallery#65]
Upon creation, you can set which user groups the config row applies to. To my knowledge, there is no way to change these settings after the config row has been created.

**Comment by Chraneco** [comment]
Is this a feature request or are you planning on working on this?
If it is a feature request please post it here instead and we will close this issue item: http://joomgallery.uservoice.com/
On the other hand if you are planning on working on this feel free to ask any questions that could help you. We appreciate any contribution to the community.

**Comment by GenaBitu** [comment]
Sorry, moved to uservoice, it is a feature request
