### ISSUE TITLE
Error in display image via view.raw.php

### ISSUE THREAD

**Issue by tosiek** [JoomGallery/JoomGallery#74]
Script add something after image so it cannot be displayed.

Temporary fix.
Add after line 249 to look like this:
header('Content-type: '.$mime);
echo JFile::read($img);
exit;

Topis on forum:
http://www.forum.en.joomgallery.net/index.php?topic=7361.0

**Comment by Erftralle** [comment]
Most probably you have a problem described here 
http://www.en.joomgallery.net/faq/general-faq/detail-original-images-arent-displayed.html
and here
http://www.en.joomgallery.net/faq/general-faq/problem-with-certain-system-plugins.html

**Comment by tosiek** [comment]
Thanks, probably Qlue 404 caused that error.


If i try to remove that package, i've got error:
Plugin Uninstall: Manifest file invalid or not found.

To remove Qlue 404 package u have to rename file (make sure this file is from Qlue 404) or upload correct file:
administrator/manifests/packages/package.xml 
to
pkg_Qlue404.xml

In attachment, original pkg_Qlue404 (change extension from .txt to .xml).

[pkg_Qlue404.txt](https://github.com/JoomGallery/JoomGallery/files/80122/pkg_Qlue404.txt)

**Comment by Chraneco** [comment]
The plugin is indeed causing the problem linked by @Erftralle, see here for a possible solution: http://www.forum.joomgallery.net/index.php?topic=4305.0

In order to solve the problem regarding the uninstall you will have to contact the developers of the plugin.
