### ISSUE TITLE
Insert image in JoomGallery category description not possible with JoomBu

### ISSUE THREAD

**Issue by MrMusic** [JoomGallery/JoomGallery#75]
DE: Das einfügen eines einzelnen Bildes in die Beschreibung einer Kategorie funktioniert nicht. Es kommt zu einem Javascript-Fehler. Das betrifft sowohl das Frontend als auch das Backend. Siehe auch hier: http://www.forum.joomgallery.net/index.php/topic,6332.0.html

EN: The insertion of a single image in the description of a category is not working. It comes to a javascript error. This concerns both the frontend and the backend. See also here: http://www.forum.joomgallery.net/index.php/topic,6332.0.html

**Comment by Chraneco** [comment]
Please test this little change in the JoomBu plugin:
https://github.com/JoomGallery/JoomBu/pull/1
