### ISSUE TITLE
Add new function to add image link as article intro or fulltext image

### ISSUE THREAD

**Issue by arjsan** [JoomGallery/JoomGallery#76]
Currently the Joomplu/Joombu plugins are only used to insert images into article. However, in real life you often want to use these images as your article intro/fulltext images. 

In order to acomplish this, there are several changes needed.

MINI.JS

here the function insertJoomPluWithId is returning the tag with window.parent.jInsertEditorText(tag, editor); . This means that whatever is specified as e_name is beeing ignored and the jInsertEditor will only return the tag into the WYSIWYG editor. 

This can be bypassed by creating a new function, which is returning a modified tag with image link only and also is returning it with window.parent.document.getElementById(editor).value = tag;

In this case, the image will be placed into the field which is beeing sent to the function.

See attached mini.js file with function insertJoomPluWithId1

DEFAULT_MINIS.PHP
administrator/components/com_joomgallery/views/mini/tmpl/

In this file we need to find out which e_name parameter is beeing passed and add an IF which will based on the e_name parameter call the correct function - either to add into WYSIWYG or add link into intro/fulltext image field.

TEMPLATE MODIFICATION

now, this is not a clean way to solve it but it did it for me. I have modified the default article edit template to add the link to the joomplu below the intro image and fulltext image fields. Just adding the text into the template for frontend edit, and for admin had to wrap it in an if and based on field just add it with right e_name parameter. 

This is not a clean way to do it! Instead of modifying the default article edit template, it would be better to add this into the joomplu code. In the options screen where you select the type of image, linked etc it would be good to select where you want to add the image - so an additional field would have to be addet to select Image target with options: Article / Intro image / Fulltext image. Based on that setting the file default_minis.php woud have to be modified and call the correct function and pass the correct e_name parameter to the javascript function.

![detailimgsel](https://cloud.githubusercontent.com/assets/16736427/12373965/6894a086-bc8d-11e5-9d0e-887005d6fb08.png)
![introfullimg](https://cloud.githubusercontent.com/assets/16736427/12373966/7570fba6-bc8d-11e5-949c-eec9cfdaf069.png)

<a class="btn modal-button" title="JoomImage" href="/administrator/index.php?option=com_joomgallery&amp;view=mini&amp;format=raw&amp;e_name=jform_images_image_intro&amp;catid=0&amp;extended=1" onclick="IeCursorFix(); return false;" rel="{handler: 'iframe', size: {x: 620, y: 550}}">
<i class="icon-picture"></i> JoomImage	</a>

[github.zip](https://github.com/JoomGallery/JoomGallery/files/93032/github.zip)

**Comment by Chraneco** [comment]
Hi @arjsan 

thanks for the suggestion!
I think I found an easier way to do this. It would be very kind if you could test it:

[media.txt](https://github.com/JoomGallery/JoomGallery/files/97862/media.txt)

Please rename this file to `media.php` and copy it into the directory `libraries/cms/form/fields/` replacing the existing `media.php` file.

The existing media selection box will then have an additional button for selecting JoomGallery images.

If your tests are successful we can create a system plugin that is adding this form field to Joomla without having to manually override the file.

**Comment by arjsan** [comment]
Ok, this looks nice, however - you removed the settings and the js is actually looking for them and thus the image link is not inserted as it fails in the js.  Also mind, that with settings removed, you can not select if you want to insert link for thumbnail or detail image. That is important as many users use thumbnail size for article intro and detail size for full article.

So at least this setting must return back and then the js function has to be corrected so that it will not fail due to missing parameters

**Comment by Chraneco** [comment]
Okay, for getting the settings back there probably requires an additional change in the gallery. We can tackle that later.

However, I did not get any JavaScript errors when I tested it. The code shouldn't even be looking for the configured image size at that point. Can you please let me know on which page exactly you tested this (frontend or backend article editor) and with which Joomla version?

**Comment by arjsan** [comment]
The javascript errors most likely are caused by the following code in the beginning of the insertJoomPluWithId function in mini.js file.  The parameters simly are missing so the js stops right there


![error_mini_js](https://cloud.githubusercontent.com/assets/16736427/12460093/4cbc8478-bfb2-11e5-9516-cc738976fb65.jpg)


    form = document.id('imagesForm');
    var link_type = radioGetCheckedValue(form.linked);
    var linked_type = radioGetCheckedValue(form.linked_type);
    var opt_class = document.getElementById('jg_bu_class').value;
    var text = document.getElementById('jg_bu_text').value;
    var alttext = document.getElementById('jg_bu_alttext').value;

**Comment by Chraneco** [comment]
In the version I tested this method is never even called because it calls a method on the main window.
That's why I'd like to know on which page exactly and with which version of Joomla you are testing this.

**Comment by arjsan** [comment]
yeah, thats the issue that I am running my custom code. I will try this on a non customized install and report back

**Comment by arjsan** [comment]
Ok, tested on Joomla 3.4.8 with Joomgallery 3.2.2 with no customization

The button works correctly at the intro image -> the link is inserted correctly

The button does not work correctly for fulltext image -> attempts to call the js method which fails

**Comment by Chraneco** [comment]
Alright, thanks!
Here are some changes:

[media.txt](https://github.com/JoomGallery/JoomGallery/files/98044/media.txt)
[default_minis.txt](https://github.com/JoomGallery/JoomGallery/files/98048/default_minis.txt)

The media file needs to be replaced as before and the other name has to be renamed to `default_minis.php` and put into folder `administrator/components/com_joomgallery/views/mini/tmpl`.

This is not yet the final solution, but it should work.

**Comment by arjsan** [comment]
Ok, this adds the link into the correct fields and works for both the intro as well as fulltext image. 

Settings seem to be ignored as the image type is beeing set as thumb, irrespective what is set in the settings view.

**Comment by Chraneco** [comment]
Maybe you have to empty the cache after the last test.
Please also keep in mind that the preview image is not displayed bigger and that the tooltip with the path does not always seem to be updated by Joomla. You need to verify the path in the input field directly.
The path looks good in any case for me.

**Comment by arjsan** [comment]
Ok, here is whats happening - if you select the intro image first, it will insert the link as selected. Then, if you select the fulltext image, it actually will update both the intro as well as fulltext image field. If you try to correct it it will keep updating both fields with the link selected.

**Comment by Chraneco** [comment]
I just made the same test with the original media form field of Joomla. The same thing is happening there, but as I said before it only affects the tooltip, the actual value of the input field is the correct one.

**Comment by arjsan** [comment]
Yes, I see, you are correct, its only the tooltip. Link itself is correct

**Comment by Chraneco** [comment]
Okay, since there is a small change necessary in JoomGallery we will have to wait with this for the next release. After that, I will create a small system plugin which is adding the new media form field to Joomla.

**Comment by Chraneco** [comment]
The latest release of JoomGallery included the small change for making this work. So here is the system plugin that once installed and enabled adds the JoomGallery button to the Joomla media form field: https://github.com/JoomGallery/JoomMediaFormField/releases
