### ISSUE TITLE
Would be nice if RSS had IMAGE url

### ISSUE THREAD

**Issue by Serrbiz** [JoomGallery/JoomGallery#82]
Would be nice if the category RSS feed had option to include the thumbnail or larger image in the actual RSS...

**Comment by Chraneco** [comment]
Hi,

please post feature requests on Uservoice: https://joomgallery.uservoice.com/forums/13274-joomgallery-feature-requests
and be a bit more specific. The RSS feed already includes a link to the detail image with certain settings enabled.
