### ISSUE TITLE
Problem with image URL on multilingual site

### ISSUE THREAD

**Issue by crumblingwalls** [JoomGallery/JoomGallery#91]
Hi, I am using JG 3.3.1 with Joomla 3.5.1 and I noticed that JG seems to have problems with multilingual sites.

If on a German/English site, for instance, the German menu item is available from »example.com/fotos« and the English item is available from »example.com/en/photos« expected behaviour would be that the image in a German language article would be fetched from »/fotos/image?...«. Instead, it is fetched from »/photos/image?...« which consequently throws a 404. 
As a workaround I have renamed the alias of the German menu item to »photos«. Is that a known issue and are you planning on fixing it?

Thanks in advance!

**Comment by Chraneco** [comment]
Hi!

Unfortunately, I was unable to reproduce this problem. Did you use an extension to make the site multilingual? Does this happen only to images in articles? Was the article created in the frontend or backend?

Regards
Chraneco

**Comment by crumblingwalls** [comment]
Hi, thanks for the answer.
No, I use native Joomla translations only, and yes, it seems to be happening only to images in articles. The articles were created from the backend.

**Comment by Chraneco** [comment]
In that case I would need a link to the page as I was not able to reproduce this with the native Joomla translations (and images have been inserted into articles using the JoomGallery editor button JoomBu).

**Comment by crumblingwalls** [comment]
Yes, images had been inserted using the JG editor button: http://crumblingwalls.net/en/integration/80470-sql-injection-mossack-fonseca-s-latest-security-flaw

**Comment by Chraneco** [comment]
The image in that article seems to be displayed fine regardless of the language.
How did you configure Joomla to not include the language code in the German language?

**Comment by crumblingwalls** [comment]
It displays fine because of the above mentioned workaround ;)
I configured the language filter plugin to exclude the prefix of the default language.

**Comment by Chraneco** [comment]
Ok, thanks! I think I found the problem. Could you please test the changes in #93?

**Comment by crumblingwalls** [comment]
Nope, doesn't seem to fix it.

**Comment by crumblingwalls** [comment]
Ok, now that I removed the default item ID from JG's configuration settings it does work ;) 
Thanks a million for the quick fix!

**Comment by Chraneco** [comment]
Alright, thanks for the feedback!
Yes, if the configured default Itemid is tied to a specific language, it cannot work. However, you should be able to enter the ID of a menu item that is not tied to a specific language. Leaving it empty would still be the better solution though.
